# Generated by Django 5.2.6 on 2025-09-27 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deputado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_parlamentar', models.CharField(max_length=255, verbose_name='Nome Parlamentar')),
                ('partido', models.CharField(max_length=50, verbose_name='Partido')),
                ('uf', models.CharField(max_length=2, verbose_name='Estado (UF)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone')),
                ('foto_url', models.URLField(blank=True, null=True, verbose_name='Foto')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Twitter/X')),
                ('latest_tweet_url', models.URLField(blank=True, null=True, verbose_name='Último Tweet')),
                ('social_media_source', models.CharField(blank=True, help_text='chamber_website, google_search, or manual', max_length=50, null=True, verbose_name='Fonte das Redes Sociais')),
                ('social_media_confidence', models.CharField(blank=True, help_text='high, medium, low', max_length=20, null=True, verbose_name='Confiança das Redes Sociais')),
                ('needs_social_media_review', models.BooleanField(default=False, verbose_name='Precisa Revisar Redes Sociais')),
                ('api_id', models.IntegerField(unique=True, verbose_name='ID na API da Câmara')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Deputado',
                'verbose_name_plural': 'Deputados',
                'ordering': ['nome_parlamentar'],
                'indexes': [models.Index(fields=['partido'], name='pressionaap_partido_b0d0f6_idx'), models.Index(fields=['uf'], name='pressionaap_uf_aeccc7_idx'), models.Index(fields=['nome_parlamentar'], name='pressionaap_nome_pa_6839bc_idx'), models.Index(fields=['is_active'], name='pressionaap_is_acti_00e5b6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Senador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_parlamentar', models.CharField(max_length=255, verbose_name='Nome Parlamentar')),
                ('partido', models.CharField(max_length=50, verbose_name='Partido')),
                ('uf', models.CharField(max_length=2, verbose_name='Estado (UF)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone')),
                ('foto_url', models.URLField(blank=True, null=True, verbose_name='Foto')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Twitter/X')),
                ('latest_tweet_url', models.URLField(blank=True, null=True, verbose_name='Último Tweet')),
                ('social_media_source', models.CharField(blank=True, help_text='chamber_website, google_search, or manual', max_length=50, null=True, verbose_name='Fonte das Redes Sociais')),
                ('social_media_confidence', models.CharField(blank=True, help_text='high, medium, low', max_length=20, null=True, verbose_name='Confiança das Redes Sociais')),
                ('needs_social_media_review', models.BooleanField(default=False, verbose_name='Precisa Revisar Redes Sociais')),
                ('api_id', models.IntegerField(unique=True, verbose_name='ID na API do Senado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Senador',
                'verbose_name_plural': 'Senadores',
                'ordering': ['nome_parlamentar'],
                'indexes': [models.Index(fields=['partido'], name='pressionaap_partido_92e477_idx'), models.Index(fields=['uf'], name='pressionaap_uf_dcc4bb_idx'), models.Index(fields=['nome_parlamentar'], name='pressionaap_nome_pa_d4cf9a_idx'), models.Index(fields=['is_active'], name='pressionaap_is_acti_f02980_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('tweet_url', models.URLField(verbose_name='URL do Tweet')),
                ('tweet_id', models.CharField(max_length=50, verbose_name='ID do Tweet')),
                ('discovered_at', models.DateTimeField(auto_now_add=True, verbose_name='Descoberto em')),
                ('position', models.PositiveSmallIntegerField(help_text='1=mais recente, 5=mais antigo', verbose_name='Posição')),
                ('tweet_text', models.TextField(blank=True, null=True, verbose_name='Texto do Tweet')),
                ('tweet_date', models.DateTimeField(blank=True, null=True, verbose_name='Data do Tweet')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('needs_content_update', models.BooleanField(default=True, verbose_name='Precisa Atualizar Conteúdo')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Tweet',
                'verbose_name_plural': 'Tweets',
                'ordering': ['content_type', 'object_id', 'position'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='pressionaap_content_9e0490_idx'), models.Index(fields=['position'], name='pressionaap_positio_573c30_idx'), models.Index(fields=['discovered_at'], name='pressionaap_discove_8a96dd_idx'), models.Index(fields=['is_active'], name='pressionaap_is_acti_10f844_idx')],
                'unique_together': {('content_type', 'object_id', 'position'), ('content_type', 'object_id', 'tweet_id')},
            },
        ),
        migrations.CreateModel(
            name='TwitterMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título da Mensagem')),
                ('message', models.TextField(help_text='Máximo 280 caracteres (limite do Twitter)', max_length=280, verbose_name='Mensagem')),
                ('category', models.CharField(choices=[('greeting', 'Saudação'), ('question', 'Pergunta'), ('opinion', 'Opinião'), ('complaint', 'Reclamação'), ('suggestion', 'Sugestão'), ('support', 'Apoio'), ('criticism', 'Crítica'), ('information_request', 'Solicitação de Informação'), ('other', 'Outro')], default='other', max_length=20, verbose_name='Categoria')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Prioridade')),
                ('hashtags', models.CharField(blank=True, help_text='Hashtags separadas por espaço (ex: #política #transparência)', max_length=200, null=True, verbose_name='Hashtags')),
                ('mentions', models.CharField(blank=True, help_text='Usuários a mencionar separados por espaço (ex: @usuario1 @usuario2)', max_length=200, null=True, verbose_name='Menções')),
                ('for_deputies', models.BooleanField(default=True, verbose_name='Para Deputados')),
                ('for_senators', models.BooleanField(default=True, verbose_name='Para Senadores')),
                ('target_parties', models.CharField(blank=True, help_text='Partidos específicos separados por vírgula (deixe vazio para todos)', max_length=500, null=True, verbose_name='Partidos Alvo')),
                ('target_states', models.CharField(blank=True, help_text='Estados específicos separados por vírgula (deixe vazio para todos)', max_length=100, null=True, verbose_name='Estados Alvo')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('ready', 'Pronto para Envio'), ('sent', 'Enviado'), ('failed', 'Falha no Envio'), ('archived', 'Arquivado')], default='draft', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='Agendado para')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='Vezes Utilizada')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Última vez utilizada')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Mensagem do Twitter',
                'verbose_name_plural': 'Mensagens do Twitter',
                'ordering': ['-created_at', 'priority'],
                'indexes': [models.Index(fields=['status'], name='pressionaap_status_ec3031_idx'), models.Index(fields=['category'], name='pressionaap_categor_ba7a2f_idx'), models.Index(fields=['priority'], name='pressionaap_priorit_e25825_idx'), models.Index(fields=['created_at'], name='pressionaap_created_6bc7b7_idx'), models.Index(fields=['scheduled_for'], name='pressionaap_schedul_93840b_idx')],
            },
        ),
    ]
