# Generated by Django 5.2.6 on 2025-10-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressionaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deputado',
            name='social_media_confidence',
            field=models.CharField(blank=True, choices=[('high', 'Alta'), ('medium', 'Média'), ('low', 'Baixa')], help_text='Nível de confiança da informação das redes sociais', max_length=20, null=True, verbose_name='Confiança das Redes Sociais'),
        ),
        migrations.AlterField(
            model_name='deputado',
            name='social_media_source',
            field=models.CharField(blank=True, choices=[('official_api', 'API Oficial'), ('chamber_website', 'Site da Câmara'), ('grok_api', 'Grok API'), ('google_search', 'Google Search'), ('manual', 'Manual')], help_text='Fonte de onde foi extraída a informação das redes sociais', max_length=50, null=True, verbose_name='Fonte das Redes Sociais'),
        ),
        migrations.AlterField(
            model_name='senador',
            name='social_media_confidence',
            field=models.CharField(blank=True, choices=[('high', 'Alta'), ('medium', 'Média'), ('low', 'Baixa')], help_text='Nível de confiança da informação das redes sociais', max_length=20, null=True, verbose_name='Confiança das Redes Sociais'),
        ),
        migrations.AlterField(
            model_name='senador',
            name='social_media_source',
            field=models.CharField(blank=True, choices=[('official_api', 'API Oficial'), ('senate_website', 'Site do Senado'), ('grok_api', 'Grok API'), ('google_search', 'Google Search'), ('manual', 'Manual')], help_text='Fonte de onde foi extraída a informação das redes sociais', max_length=50, null=True, verbose_name='Fonte das Redes Sociais'),
        ),
    ]
