# Generated by Django 5.2.6 on 2025-09-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deputado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_parlamentar', models.CharField(max_length=255, verbose_name='Nome Parlamentar')),
                ('partido', models.CharField(max_length=50, verbose_name='Partido')),
                ('uf', models.CharField(max_length=2, verbose_name='Estado (UF)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone')),
                ('foto_url', models.URLField(blank=True, null=True, verbose_name='Foto')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Twitter/X')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='YouTube')),
                ('tiktok_url', models.URLField(blank=True, null=True, verbose_name='TikTok')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('social_media_source', models.CharField(blank=True, help_text='chamber_website, google_search, or manual', max_length=50, null=True, verbose_name='Fonte das Redes Sociais')),
                ('social_media_confidence', models.CharField(blank=True, help_text='high, medium, low', max_length=20, null=True, verbose_name='Confiança das Redes Sociais')),
                ('needs_social_media_review', models.BooleanField(default=False, verbose_name='Precisa Revisar Redes Sociais')),
                ('api_id', models.IntegerField(unique=True, verbose_name='ID na API da Câmara')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Deputado',
                'verbose_name_plural': 'Deputados',
                'ordering': ['nome_parlamentar'],
                'indexes': [models.Index(fields=['partido'], name='blindagemap_partido_accc56_idx'), models.Index(fields=['uf'], name='blindagemap_uf_eb8bfb_idx'), models.Index(fields=['nome_parlamentar'], name='blindagemap_nome_pa_b298ea_idx'), models.Index(fields=['is_active'], name='blindagemap_is_acti_3c2632_idx')],
            },
        ),
        migrations.CreateModel(
            name='Senador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_parlamentar', models.CharField(max_length=255, verbose_name='Nome Parlamentar')),
                ('partido', models.CharField(max_length=50, verbose_name='Partido')),
                ('uf', models.CharField(max_length=2, verbose_name='Estado (UF)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone')),
                ('foto_url', models.URLField(blank=True, null=True, verbose_name='Foto')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Twitter/X')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='YouTube')),
                ('tiktok_url', models.URLField(blank=True, null=True, verbose_name='TikTok')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('social_media_source', models.CharField(blank=True, help_text='chamber_website, google_search, or manual', max_length=50, null=True, verbose_name='Fonte das Redes Sociais')),
                ('social_media_confidence', models.CharField(blank=True, help_text='high, medium, low', max_length=20, null=True, verbose_name='Confiança das Redes Sociais')),
                ('needs_social_media_review', models.BooleanField(default=False, verbose_name='Precisa Revisar Redes Sociais')),
                ('api_id', models.IntegerField(unique=True, verbose_name='ID na API do Senado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Senador',
                'verbose_name_plural': 'Senadores',
                'ordering': ['nome_parlamentar'],
                'indexes': [models.Index(fields=['partido'], name='blindagemap_partido_78c5b2_idx'), models.Index(fields=['uf'], name='blindagemap_uf_61279e_idx'), models.Index(fields=['nome_parlamentar'], name='blindagemap_nome_pa_739991_idx'), models.Index(fields=['is_active'], name='blindagemap_is_acti_5da36e_idx')],
            },
        ),
    ]
