# Generated by Django 5.2.6 on 2025-09-19 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deputado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_civil', models.CharField(max_length=255, verbose_name='Nome Civil')),
                ('nome_parlamentar', models.CharField(max_length=255, verbose_name='Nome Parlamentar')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('partido', models.CharField(max_length=50, verbose_name='Partido')),
                ('uf', models.CharField(max_length=2, verbose_name='Estado (UF)')),
                ('legislatura', models.CharField(max_length=20, verbose_name='Legislatura')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('naturalidade', models.CharField(blank=True, max_length=255, null=True)),
                ('profissao', models.CharField(blank=True, max_length=255, null=True)),
                ('escolaridade', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=50, null=True)),
                ('site', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Twitter/X')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('youtube_url', models.URLField(blank=True, null=True, verbose_name='YouTube')),
                ('tiktok_url', models.URLField(blank=True, null=True, verbose_name='TikTok')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('gabinete', models.CharField(blank=True, max_length=50, null=True)),
                ('comissoes', models.TextField(blank=True, help_text='Comissões que participa', null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('foto_url', models.URLField(blank=True, null=True)),
                ('id_deputado_camara', models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID na Câmara')),
                ('uri_camara', models.URLField(blank=True, null=True, verbose_name='URI na API da Câmara')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Deputado',
                'verbose_name_plural': 'Deputados',
                'ordering': ['nome_parlamentar'],
                'indexes': [models.Index(fields=['legislatura', 'partido'], name='blindagemap_legisla_c24455_idx'), models.Index(fields=['uf'], name='blindagemap_uf_eb8bfb_idx'), models.Index(fields=['nome_parlamentar'], name='blindagemap_nome_pa_b298ea_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistoricoMandato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legislatura', models.CharField(max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('situacao', models.CharField(max_length=100)),
                ('condicao', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deputado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_mandatos', to='blindagemapp.deputado')),
            ],
            options={
                'verbose_name': 'Histórico de Mandato',
                'verbose_name_plural': 'Históricos de Mandatos',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
