# Generated by Django 5.2.6 on 2025-09-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blindagemapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deputado',
            name='foto_url',
            field=models.URLField(blank=True, null=True, verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='senador',
            name='foto_url',
            field=models.URLField(blank=True, null=True, verbose_name='Foto'),
        ),
    ]
