# Generated by Django 5.2.6 on 2025-09-25 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blindagemapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título da Mensagem')),
                ('message', models.TextField(help_text='Máximo 280 caracteres (limite do Twitter)', max_length=280, verbose_name='Mensagem')),
                ('category', models.CharField(choices=[('greeting', 'Saudação'), ('question', 'Pergunta'), ('opinion', 'Opinião'), ('complaint', 'Reclamação'), ('suggestion', 'Sugestão'), ('support', 'Apoio'), ('criticism', 'Crítica'), ('information_request', 'Solicitação de Informação'), ('other', 'Outro')], default='other', max_length=20, verbose_name='Categoria')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Prioridade')),
                ('hashtags', models.CharField(blank=True, help_text='Hashtags separadas por espaço (ex: #política #transparência)', max_length=200, null=True, verbose_name='Hashtags')),
                ('mentions', models.CharField(blank=True, help_text='Usuários a mencionar separados por espaço (ex: @usuario1 @usuario2)', max_length=200, null=True, verbose_name='Menções')),
                ('for_deputies', models.BooleanField(default=True, verbose_name='Para Deputados')),
                ('for_senators', models.BooleanField(default=True, verbose_name='Para Senadores')),
                ('target_parties', models.CharField(blank=True, help_text='Partidos específicos separados por vírgula (deixe vazio para todos)', max_length=500, null=True, verbose_name='Partidos Alvo')),
                ('target_states', models.CharField(blank=True, help_text='Estados específicos separados por vírgula (deixe vazio para todos)', max_length=100, null=True, verbose_name='Estados Alvo')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('ready', 'Pronto para Envio'), ('sent', 'Enviado'), ('failed', 'Falha no Envio'), ('archived', 'Arquivado')], default='draft', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('scheduled_for', models.DateTimeField(blank=True, null=True, verbose_name='Agendado para')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='Vezes Utilizada')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Última vez utilizada')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Mensagem do Twitter',
                'verbose_name_plural': 'Mensagens do Twitter',
                'ordering': ['-created_at', 'priority'],
                'indexes': [models.Index(fields=['status'], name='blindagemap_status_98220c_idx'), models.Index(fields=['category'], name='blindagemap_categor_89df61_idx'), models.Index(fields=['priority'], name='blindagemap_priorit_369e52_idx'), models.Index(fields=['created_at'], name='blindagemap_created_064b16_idx'), models.Index(fields=['scheduled_for'], name='blindagemap_schedul_d954e5_idx')],
            },
        ),
    ]
